function [scenario, egoVehicle] = mooseTes()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.14 (R2023a) and Automated Driving Toolbox 3.7 (R2023a).
% Generated on: 30-Jan-2026 15:14:34

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-0.02 0 0;
    12 0 0];
roadWidth = 2;
road(scenario, roadCenters, roadWidth, 'Name', 'Road');

roadCenters = [12 1 0;
    25.5 1 0];
roadWidth = 4;
road(scenario, roadCenters, roadWidth, 'Name', 'Road1');

roadCenters = [25.5 1.7 0;
    36 1.7 0];
roadWidth = 2.6;
road(scenario, roadCenters, roadWidth, 'Name', 'Road2');

roadCenters = [36 1 0;
    48.5 1 0];
roadWidth = 4;
road(scenario, roadCenters, roadWidth, 'Name', 'Road3');

roadCenters = [48.5 0.5 0;
    58.54 0.5 0];
roadWidth = 3;
road(scenario, roadCenters, roadWidth, 'Name', 'Road4');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Length', 2.8, ...
    'Width', 1.6, ...
    'Position', [1 0.00984910213151236 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [1 0.00984910213151236 0.01;
    7.12 -0.13 0.01;
    13.45 -0.04 0.01;
    14.69 0.03 0.01;
    15.74 0.23 0.01;
    16.9 0.51 0.01;
    18.04 0.84 0.01;
    19.29 1.23 0.01;
    20.61 1.56 0.01;
    23.31 1.87 0.01;
    25.12 1.87 0.01;
    29.13 1.79 0.01;
    36.02 1.62 0.01;
    38.17 1.23 0.01;
    39.23 1.05 0.01;
    40.33 0.86 0.01;
    41.94 0.69 0.01;
    44.54 0.49 0.01;
    47.47 0.42 0.01;
    58.59 0.54 0];
speed = [20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20;20];
yaw =  [1;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN;NaN];
trajectory(egoVehicle, waypoints, speed, 'Yaw', yaw);

